services:
  postgres:
    image: postgres:17
    container_name: linkup-postgres

    environment:
      POSTGRES_USER: linkup
      POSTGRES_PASSWORD: linkup_dev_password
      POSTGRES_DB: linkup

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: